- name: uninstall docker
  hosts: localhost
  vars_files:
    - data.yml
  tasks:
    - name: uninstall apt package
      include_tasks:
        file: ../../library/tasks/uninstall_apt_package.yml
      loop: "{{ names }}"
      loop_control:
        loop_var: name
